#!/bin/bash
basedir=$(cd "$(dirname "$0")/../lib" && pwd)

if [ -d "$basedir/quickview" ]; then
    rootdir="$basedir/quickview"
elif [ -d "$basedir/quick-view" ]; then
    rootdir="$basedir/quick-view"
else
    echo "Error: Could not find quickview or quick-view directory in $basedir" >&2
    exit 1
fi

"$rootdir/server/server" "$@"
